version: '3.0'
services:
   mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./docker-mosquitto/mosquitto/config:/mosquitto/config/
      - ./docker-mosquitto/mosquitto/data:/mosquitto/data/
      - ./docker-mosquitto/mosquitto/log:/mosquitto/log/
    ports:
      - 3000:3000  